services:
  - type: web
    name: users-app
    buildCommand: yarn --frozen-lockfile install; yarn build
    startCommand: node --max-old-space-size=512 dist/main
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000